spring:
#  profiles:
#    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.8.210:3306/user
    username: hcl
    password: 111111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
#qq个人邮箱
       host: smtp.qq.com
#qq企业邮箱
#       host: smtp.exmail.qq.com
       username: chenglong.he@foxmail.com
       password: txbcyukymegpcajf

#       recipients: 378488249@qq.com,648568780@qq.com,chenglong.he@foxmail.com
       properties:
         mail:
           smtp:
             auth: true
             starttls:
               enable: true
               required: true

girl:
  age: 11
  name: blue
age: 11
name: blue

#邮件接收人者，多个用英文逗号隔开
mailRecipients: 378488249@qq.com,648568780@qq.com,chenglong.he@foxmail.com

server:
#端口号
#  port: 8082
#  命名空间
#  context-path: /boot
